name: "Codesphere Deploy"
description: "Deploys the repository in Codesphere using the Codesphere REST API"
branding:
  icon: "circle"
  color: "purple"

inputs:
  token:
    description: >
      Codesphere API token for authentication.
      Generate one from your Codesphere account settings.
    required: true
  teamId:
    description: >
      Numeric ID of the Codesphere team.
      Find your team ID via `cs list teams` or in the Codesphere UI.
    required: true
  planId:
    description: |
      Numeric plan ID for the workspace.

      Discover available plans with `cs list plans`.
    required: false
    default: "8"
  env:
    description: |
      Environment variables to set in the workspace.
      One variable per line in KEY=VALUE format.

      Example:
        MY_VAR=hello
        MY_SECRET=<your-secret-value>
    required: false
  vpnConfig:
    description: >
      Name of the VPN config the workspace should connect to.
      The VPN configuration must be set up in the team beforehand.
    required: false
  apiUrl:
    description: "Codesphere API URL (must include /api path)"
    required: false
    default: "https://codesphere.com/api"
  branch:
    description: >
      Git branch to deploy.
      Auto-detected from the PR head branch or push ref if not specified.
    required: false
  stages:
    description: >
      Pipeline stages to run after deployment.
      Space-separated list of: prepare, test, run.
    required: false
    default: "prepare run"

runs:
  using: "node20"
  main: "main.js"

outputs:
  deployment-url:
    description: "URL of the deployed workspace (https://<dev-domain>)"
  workspace-id:
    description: "Numeric ID of the created/updated workspace"
