name: "Codesphere Deploy"
description: "Deploys the repository in Codesphere using the Codesphere CLI (cs-go)"
branding:
  icon: "circle"
  color: "purple"

inputs:
  token:
    description: >
      Codesphere API token for authentication.
      Generate one from your Codesphere account settings.
    required: true
  teamId:
    description: >
      Numeric ID of the Codesphere team.
      Find your team ID via `cs list teams` or in the Codesphere UI.
    required: true
  planId:
    description: |
      Numeric plan ID for the workspace.

      Discover available plans with `cs list plans`.
    required: false
    default: "8"
  env:
    description: |
      Environment variables to set in the workspace.
      One variable per line in KEY=VALUE format.

      Example:
        MY_VAR=hello
        MY_SECRET=<your-secret-value>
    required: false
  vpnConfig:
    description: >
      Name of the VPN config the workspace should connect to.
      The VPN configuration must be set up in the team beforehand.
    required: false
  apiUrl:
    description: "Codesphere API URL"
    required: false
    default: "https://codesphere.com"
  branch:
    description: >
      Git branch to deploy.
      Auto-detected from the PR head branch or push ref if not specified.
    required: false

runs:
  using: "composite"
  steps:
    - name: Deploy to Codesphere
      shell: bash
      env:
        CS_TOKEN: ${{ inputs.token }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TEAMID: ${{ inputs.teamId }}
        INPUT_PLANID: ${{ inputs.planId }}
        INPUT_ENV: ${{ inputs.env }}
        INPUT_VPNCONFIG: ${{ inputs.vpnConfig }}
        INPUT_APIURL: ${{ inputs.apiUrl }}
        INPUT_BRANCH: ${{ inputs.branch }}
        PR_ACTION: ${{ github.event.action }}
      run: bash ${{ github.action_path }}/entrypoint.sh

outputs: {}
